# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#files: ^SCM/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
        exclude: "mkdocs.yml"
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        args: ["--line-length=150"]
        files: .
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ["--ignore=E203, W503, E501, E722"]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: .
